# Generated by Django 6.0.6 on 2026-06-30 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_new', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=50)),
                ('attended', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Meeting', 'Meeting'), ('Demo', 'Demo'), ('Follow-up', 'Follow-up')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20)),
                ('lead_status', models.CharField(default='new', max_length=50)),
                ('completion_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
