# Generated by Django 6.0.6 on 2026-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="sl_no",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="activity",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry"),
                    ("opportunity", "Opportunity"),
                    ("hot", "Hot"),
                    ("on_hold", "On Hold"),
                    ("not_responding", "Not Responding"),
                    ("not_reachable", "Not Reachable"),
                    ("dead", "Dead"),
                    ("junk", "Junk"),
                    ("repeated_lead", "Repeated Lead"),
                    ("converted", "Converted"),
                ],
                default="enquiry",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry"),
                    ("opportunity", "Opportunity"),
                    ("hot", "Hot"),
                    ("on_hold", "On Hold"),
                    ("not_responding", "Not Responding"),
                    ("not_reachable", "Not Reachable"),
                    ("dead", "Dead"),
                    ("junk", "Junk"),
                    ("repeated_lead", "Repeated Lead"),
                    ("converted", "Converted"),
                ],
                default="enquiry",
                max_length=50,
            ),
        ),
    ]
