# Generated by Django 6.0.6 on 2026-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_sl_no_alter_activity_lead_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="phone_country_code",
            field=models.CharField(blank=True, default="+91", max_length=8),
        ),
        migrations.AddField(
            model_name="lead",
            name="secondary_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="lead",
            name="secondary_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="lead",
            name="secondary_phone_country_code",
            field=models.CharField(blank=True, default="+91", max_length=8),
        ),
        migrations.AlterField(
            model_name="activity",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("enquiry", "Enquiry"),
                    ("opportunity", "Opportunity"),
                    ("hot", "Hot"),
                    ("on_hold", "On Hold"),
                    ("not_responding", "Not Responding"),
                    ("not_reachable", "Not Reachable"),
                    ("dead", "Dead"),
                    ("junk", "Junk"),
                    ("repeated_lead", "Repeated Lead"),
                    ("converted", "Converted"),
                ],
                default="new_lead",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("enquiry", "Enquiry"),
                    ("opportunity", "Opportunity"),
                    ("hot", "Hot"),
                    ("on_hold", "On Hold"),
                    ("not_responding", "Not Responding"),
                    ("not_reachable", "Not Reachable"),
                    ("dead", "Dead"),
                    ("junk", "Junk"),
                    ("repeated_lead", "Repeated Lead"),
                    ("converted", "Converted"),
                ],
                default="new_lead",
                max_length=50,
            ),
        ),
    ]
