# Generated by Django 6.0.6 on 2026-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_phone_country_code_lead_secondary_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="price_quoted",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
