# Generated by Django 6.0.6 on 2026-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_lead_owner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="owner_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
