# Generated by Django 6.0.6 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0006_lead_owner_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
