# Generated by Django 6.0.6 on 2026-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_lead_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="course_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
